# Generated by Django 4.1.2 on 2022-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_merchant_id_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
